### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by claudiotaragnolini** [FacetWP/facetwp-cmb2#5]
Hi, i downloaded and activate plugin. when i try to activate i get the following error:

Parse error: syntax error, unexpected '$skip_index' (T_VARIABLE) in /web/htdocs/www.goodfoodadvisors.com/home/wp-content/plugins/facetwp-pods-master/facetwp-pods.php on line 157

**Comment by mgibbs189** [comment]
@claudiotaragnolini we don't maintain `facetwp-pods` which appears to be the cause of the issue. My guess is just a [missing semicolon](https://github.com/pods-framework/facetwp-pods/blob/master/facetwp-pods.php#L148) in the code /cc @sc0ttkclark

**Comment by sc0ttkclark** [comment]
Actually facetwp-pods is totally not functional/tested, it's a work in progress. Not ready for consumption yet @claudiotaragnolini, sorry!
